// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM1JGvNvKmGMXRTuzqQ6PJ5fDz8Q2K9ZY',
    appId: '1:139428268637:web:73fc8e697a34ab14469bb4',
    messagingSenderId: '139428268637',
    projectId: 'chat-app-2eb15',
    authDomain: 'chat-app-2eb15.firebaseapp.com',
    storageBucket: 'chat-app-2eb15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFn9047ghmjXDpwWG3_lkiGaqTPtPHeaA',
    appId: '1:139428268637:android:464288cd68b7efd5469bb4',
    messagingSenderId: '139428268637',
    projectId: 'chat-app-2eb15',
    storageBucket: 'chat-app-2eb15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2TPW_BmdeCTVVYBqZcndGKSnGQKixrE',
    appId: '1:139428268637:ios:ed1cda1c168a629b469bb4',
    messagingSenderId: '139428268637',
    projectId: 'chat-app-2eb15',
    storageBucket: 'chat-app-2eb15.appspot.com',
    androidClientId: '139428268637-s0dv8gkgs1abelc4ts8r0nlrd1gsnd8l.apps.googleusercontent.com',
    iosClientId: '139428268637-kbfl8j9mfirlgko8g3cr5ao7oi1vfhv7.apps.googleusercontent.com',
    iosBundleId: 'com.pratham.chatapp',
  );

}